# NEWS {#booknews}

## dev version

- 2025-04-03, document how to put the system on vacation(#865)

- 2025-04-03, add details about MEE process and structure the author guide a bit more (`@robitalec`, #862)

- 2025-03-11, add note in the packaging guide about checking maintenance status of dependencies (#881)

- 2025-03-11, add item about "top level code" in packaging guide (#879)
 
- 2025-03-11, explicitly mention need to acknowledge authors of bundled code (#873)

- 2025-03-27, add guidance for packages wrapping external software (#866)

- 2025-02-25, add official rule on submitting one package at once only (`@maurolepore`, #876)

- 2025-03-11, mention the Air formatting tool wherever we mention the styler package (#875)

- 2025-02-25, require the default git branch to not be called master (#863)

- 2024-09-06, update math guidance for pkgdown based on pkgdown's update (#838)

- 2024-08-30, remove mention of Twitter since rOpenSci no longer maintains an active Twitter account (`@yabellini`, #827)

- 2024-07-17, document dashboard in editors' chapter (`@mpadge`, #829)

- 2024-06-27, document the author's submit response step in the author guide (`@jmaspons`, #832).

## 0.9.0

- 2024-01-09, update roxygen2 wording (`@vincentvanhees`, #792).

- 2023-12-15, update roxygen2 advice, mainly linking to roxygen2 website (#750).

- 2023-09-15, add suggestions for API packages (#496).

- Translation to Spanish!

- 2023-07-17, Update Aims and Scope to include translation packages, remove experimental text-processing categories, and provide clarifications around API wrappers

- 2023-05-04, Added link to Bioconductor book (#663, `@llrs`).

- 2023-04-26, Changed suggested lifecycle stage in authors guide (#661, `@bart1`).

- 2023-04-25, changed the COI section to use parallel construction (#659, `@eliocamp`).
 
- 2022-07-04, Add resources around GitHub workflows (#479, `@maurolepore`).

- 2023-02-14, update instructions for CITATION to reflect new CRAN policies (#604, #609).

- 2023-02-14, add package maintainer cheatsheet (#608).

- 2023-01-25, add Mastodon as social media (#592, by @yabellini).

- 2023-01-25, add Mastodon as social media (#592, by `@yabellini`).

- 2023-01-20, fix small formating error (#590 by `@eliocamp`).

- 2022-11-22, mention shinytest2 near shinytest.

- 2022-09-20, add editor instruction to add "stats" label to stats submissions

- 2022-09-20, fixed link to reviewer approval template (#548), and rendering of editor's template (#547)

- 2022-08-23, add recommendation to document argument default (`@Bisaloo`, #501)

- 2022-08-06, fix link to R Packages book (#498)

- 2022-07-21, mention GitHub Discussions and GitHub issue templates. (#482)

- 2022-07-21, highlight values for reviewing in more places (#481)

- 2022-07-20, Explanation of package submission via non-default branches (#485), added `@s3alfisc` to contributor list.

- 2022-07-20, add how to volunteer as a reviewer (#457).

- 2022-06-23, Expanded explanation of Codecov, added `@ewallace` to contributor list (#484)

## 0.8.0

- 2022-06-03, Remove former references to now-archived "rodev" package

- 2022-05-30, Advise that reviewers can also directly call `@ropensci-review-bot check package`

- 2022-05-27, Add Mark Padgham to list of authors

- 2022-05-27, Add `devguider::prerelease_checklist` item to pre-release template (#463)

- 2022-05-13, Align version number in DESCRIPTION file with actual version (#443)

- 2022-05-13, Update guidelines for CONTRIBUTING.md (#366, #462)

- 2022-05-09, Add section on authorship of included code, thanks to `@KlausVigo` (#388).

- 2022-05-09, Remove mention of 'rev' role requiring R v3.5

- 2022-05-05, Move all scripts from local `inst` directory to `ropensci-org/devguider` pkg.

- 2022-05-03, Update package archiving guidance to reduce README to minimal form.

- 2022-04-29, Advise that authors can directly call `@ropensci-review-bot check package`.

- 2022-04-29, Describe `pkgcheck-action` in CI section.

- 2022-04-29, Update scope in policies section to include statistical software.

- 2022-04-29, Add `prelease.R` script to open pre-release GitHub issue & ref in appendix.

- 2022-04-26, Add GitHub 2FA recommendation to package security.

- 2022-03-29, Remove references to Stef Butland, former community manager.

- 2022-03-28, Add comments on submission planning about time commitment.

- 2022-03-24, Remove approval comment template (coz it's automatically generated by the bot now).

- 2022-03-21, rephrase CITATION guidance to make it less strict. Also mentions CITATION.cff and the cffr package.

- 2022-03-08, add links to blogs related to package development (#389).

- 2022-02-17, update redirect instructions (`@peterdesmet`, #387).

- 2022-02-14, link to Michael Lynch's post Why Good Developers Write Bad Unit Tests.

- 2022-02-14, mention more packages for testing like dittodb, vcr, httptest, httptest2, webfakes.

- 2022-01-10, make review templates R Markdown files (`@Bisaloo`, #340).

- 2022-01-14, update guidance on CI services (#377)

- 2022-01-11, update guidance around branches, with resources suggested by `@ha0ye` and `@statnmap`.

- 2022-01-10, divide author's guide into sub-sections, and add extra info including `pkgcheck`.

* 2021-11-30, adds links to examples of reviews, especially tough but constructive ones (with help from `@noamross`, `@mpadge`, #363).

* 2021-11-19, add recommended spatial packages to scaffolding section (software-review-meta#47)

* 2021-11-18, update advice on grouping functions for pkgdown output (#361)

## 0.7.0

* 2021-11-04, add mentions of stat software review to software review intro and to the first book page (#342).

* 2021-11-04, mention pkgcheck in the author guide (@mpadge, #343).

* 2021-11-04, add editors' responsibilities including  Editor etiquette for commenting on packages on which you aren't handling/reviewing (@jhollist, #354). 

* 2021-11-04, give precise examples of tools for installation instructions (remotes, pak, R-universe).

* 2021-11-04, add more bot guidance (less work for editors).

* 2021-10-07, add guidance for editorial management (recruiting, inviting, onboarding, offboarding editors).

* 2021-09-14, add a requirement that there is at least one _HTML_ vignette.

* 2021-09-03, add some recommendations around git. (@annakrystalli, #341)

* 2021-07-14, clarify the categories data extraction and munging by adding examples. (@noamross, #337)

* 2021-05-20, add guidance around setting up your package to foster a community, inspired by the recent rOpenSci community call. (with help from `@Bisaloo`, #289, #308)

* 2021-04-27, no longer ask reviewers to ask covr as it'll be done by automatic tools, but ask them to pay attention to tests skipped.

* 2021-04-02, add citation guidance.

* 2021-04-02, stop asking reviewers to run goodpractice as this is part of editorial checks.

* 2021-03-23, launched a new form for reviewer volunteering.

* 2021-02-24, add guidance around the use of `@ropensci-review-bot`.

## 0.6.0

* 2021-02-04, add guidance to enforce package versioning and tracking of changes through review (`@annakrystalli`, #305)

* 2021-01-25, add a translation of the review template in Spanish (`@Fvd`, `@maurolepore`, #303)

* 2021-01-25, the book has now better citation guidance in case you want to cite this very guide (`@Bisaloo`, #304).

* 2021-01-12, add some more guidance on escaping examples (#290).

* 2021-01-12, mention the lifecycle package in the chapter about package evolution (#287).

* 2021-01-12, require overlap information is put in documentation (#292).

* 2021-01-12, start using the bookdown::bs4_book() template.

* 2021-01-12, add a sentence about whether it is acceptable to push a new version of a package to CRAN within two weeks of the most recent version if you have just been made aware of, and fixed, a major bug (`@sckott`, #283)

* 2021-01-12, mention the HTTP testing in R book.

* 2021-01-12, mention testthat snapshot tests.

* 2021-01-12, remove mentions of Travis CI and link to Jeroen Ooms' blog post about moving away from Travis.

* 2021-01-12, update the package curation policy: mention a possible exception for legacy packages that are vital parts of the R and/or rOpenSci package ecosystem which are actively monitored by staff. (`@noamross`, #293)

## 0.5.0

* 2020-10-08, add help about link checking (`@sckott`, #281)

* 2020-10-08, update JOSS instructions (`@karthik`, #276)

* 2020-10-05, add links to licence resources (`@annakrystalli`, #279)

* 2020-10-05, update information about the contributing guide (`@stefaniebutland`, #280)

* 2020-09-11, make reviewer approval a separate template (`@bisaloo`, #264)

* 2020-09-22, add package curation policy (`@noamross`, #263)

* 2020-09-11, add more guidance and requirements for docs at submission (`@annakrystalli`, #261)

* 2020-09-14, add more guidance on describing data source in DESCRIPTION (`@mpadge`, #260)

* 2020-09-14, add more guidance about tests of deprecated functions (`@sckott`, #213)

* 2020-09-11, update the CI guidance (`@bisaloo`, `@mcguinlu`, #269)

* 2020-09-11, improve the redirect guidance (`@jeroen`, `@mcguinlu`, #269)

## 0.4.0

* 2020-04-02, give less confusing code of conduct guidance: the reviewed packages' COC is rOpenSci COC (`@Bisaloo`, `@cboettig`, #240)

* 2020-03-27, add section on Ethics, Data Privacy and Human Subjects Research to Policies chapter

* 2020-03-12, mention GitHub Actions as a CI provider.

* 2020-02-24, add guide for inviting a guest editor.

* 2020-02-14, add mentions of the ropensci-books GitHub organisation and associated subdomain.

* 2020-02-10, add field and laboratory reproducibility tools as a category in scope.

* 2020-02-10, add more guidance about secrets and package development in the security chapter.

* 2020-02-06, add guidance about Bioconductor dependencies (#246).

* 2020-02-06, add package logo guidance (#217).

* 2020-02-06, add one CRAN gotcha: single quoting software names(#245, [`@aaronwolen`](https://github.com/aaronwolen))

* 2020-02-06, improve guidance regarding the replacement of "older" pkgdown website links and source (#241, [`@cboettig`](https://github.com/cboettig))

* 2020-02-06, rephrase the EiC role (#244).

* 2020-02-06, remove the recommendation to add rOpenSci footer (https://github.com/ropensci/software-review-meta/issues/79).

* 2020-02-06, remove the recommendation to add a review mention to DESCRIPTION but recommends mentioning the package version when reviewers are added as "rev" authors.

* 2020-01-30, slightly changes the advice on documentation re-use: add a con; mention `@includeRmd` and `@example`; correct the location of Rmd fragments (#230).

* 2020-01-30, add more guidance for the editor in charge of a dev guide release (#196, #205).

* 2020-01-22, add guidance in the editor guide about not transferred repositories.

* 2020-01-22, clarify forum guidance (for use cases and in general).

* 2020-01-22, mention an approach for pre-computing vignettes so that the pkgdown website might get build on rOpenSci docs server.

* 2020-01-22, document the use of mathjax with rotemplate ([`@Bisaloo`](https://github.com/Bisaloo), #199).

* 2020-01-20, add guidance for off-thread interaction and COIs ([`@noamross`](https://github.com/noamross), #197).

* 2020-01-20, add advice on specifying dependency minimum versions ([`@karthik`](https://github.com/karthik), [`@annakrystalli`](https://github.com/annakrystalli), #185).

* 2020-01-09, start using GitHub actions instead of Travis for deployment.

* -2019-12-11, add note in Documentation sub-section of Packaging Guide section about referencing the new R6 support in roxygen2 (ropensci/dev_guide#189)

* 2019-12-11, add new CRAN gotcha about having 'in R' or 'with R' in your package title ([`@bisaloo`](https://github.com/Bisaloo), ropensci/dev_guide#221)

## 0.3.0

* 2019-10-03, include in the approval template that maintainers should include link to the docs.ropensci.org/pkg site (ropensci/dev_guide#191)

* 2019-09-26, add instructions for handling editors to nominate packages for blog posts (ropensci/dev_guide#180)

* 2019-09-26, add chapter on changing package maintainers (ropensci/dev_guide#128) (ropensci/dev_guide#194)

* 2019-09-26, update Slack room to use for editors (ropensci/dev_guide#193)

* 2019-09-11, update instructions in README for rendering the book locally (ropensci/dev_guide#192)

* 2019-08-05, update JOSS submission instructions (ropensci/dev_guide#187)

* 2019-07-22, break "reproducibility" category in policies into component parts. (ropensci/software-review-meta#81)

* 2019-06-18, add link to rOpenSci community call "Security for R" to security chapter.

* 2019-06-17, fix formatting of Appendices B-D in the pdf version of the book (bug report by [`@IndrajeetPatil`](https://github.com/IndrajeetPatil), #179)

* 2019-06-17, add suggestion to use R Markdown hunks approach when the README and the vignette share content. (ropensci/dev_guide#161)

* 2019-06-17, add mention of central building of documentation websites.

* 2019-06-13, add explanations of CRAN checks. (ropensci/dev_guide#177)

* 2019-06-13, add mentions of the `rodev` helper functions where relevant.

* 2019-06-13, add recommendation about using `cat` for `str.*()` methods.  RStudio assumes that `str` uses `cat`, if not when loading an R object the `str` prints to the console in RStudio and doesn't show the correct object structure in the properties. ([`@mattfidler`] (https://github.com/mattfidler/) #178)

* 2019-06-12, add more details about git flow.

* 2019-06-12, remove recommendation about `roxygen2` dev version since the latest stable version has what is needed. ([`@bisaloo`](https://github.com/bisaloo/), #165)

* 2019-06-11, add mention of usethis functions for adding testing or vignette infrastructure in the part about dependencies in the package building guide.

* 2019-06-10, use the new URL for the dev guide, https://devguide.ropensci.org/

* 2019-05-27, add more info about the importance of the repo being recognized as a R package by linguist ([`@bisaloo`](https://github.com/bisaloo/), #172)

* 2019-05-22, update all links eligible to HTTPS and update links to the latest versions of Hadley Wickham and Jenny Bryan's books ([`@bisaloo`](https://github.com/bisaloo/), #167)

* 2019-05-15, add book release guidance for editors. (ropensci/dev_guide#152)

## 0.2.0

* 2019-05-23, add CRAN gotcha: in the Description field of your DESCRIPTION file, enclose URLs in angle brackets.

* 2019-05-13, add more content to the chapter about contributing.

* 2019-05-13, add more precise instructions about blog posts to approval template for editors.

* 2019-05-13, add policies allowing using either `<-` or `=` within a package as long as the whole package is consistent.

* 2019-05-13, add request for people to tell us if they use our standards/checklists when reviewing software elsewhere.

* 2019-04-29, add requirement and advice on testing packages using `devel` and `oldrel` R versions on Travis.

* 2019-04-23, add a sentence about why being generous with attributions and more info about ctb vs aut.

* 2019-04-23, add link to Daniel Nüst's notes about migration from XML to xml2.

* 2019-04-22, add use of rOpenSci forum to maintenance section.

* 2019-04-22, ask reviewer for consent to be added to DESCRIPTION in review template.

* 2019-04-22, use a darker blue for links (feedback by [`@kwstat`](https://github.com/kwstat), #138).

* 2019-04-22, add book cover.

* 2019-04-08, improve formatting and link text in README ([`@katrinleinweber`](https://github.com/katrinleinweber), #137)

* 2019-03-25, add favicon ([`@wlandau`](https://github.com/wlandau), #136).

* 2019-03-21, improve Travis CI guidance, including link to examples. ([`@mpadge`](https://github.com/mpadge), #135)

* 2019-02-07, simplify code examples in Package Evolution section (maintenance_evolution.Rmd file) ([`@hadley`](https://github.com/hadley), #129).

* 2019-02-07, added a PDF file to export (request by [`@IndrajeetPatil`](https://github.com/IndrajeetPatil), #131).

## 0.1.5

* 2019-02-01, created a .zenodo.json to explicitly set editors as authors.

## First release 0.1.0

* 2019-01-23, add details about requirements for packages running on all major platforms and added new section to package categories.

* 2019-01-22, add details to the guide for authors about the development stage at which to submit a package.

* 2018-12-21, inclusion of an explicit policy for conflict of interest (for reviewers and editors).

* 2018-12-18, added more guidance for editor on how to look for reviewers.

* 2018-12-04, onboarding was renamed Software Peer Review.

## place-holder 0.0.1

* Added a `NEWS.md` file to track changes to the book.
