---
repo-actions: yes
aliases: 
  - marketing.html
---

# Marketing do seu pacote {#marketing}

```{block, type="summaryblock"}
Ajudaremos você a promover seu pacote, mas aqui estão mais algumas coisas que você deve ter em mente.
```

- Se você souber de um caso de uso do seu pacote, incentive o autor a publicar o link em nosso [fórum de discussão na categoria Casos de](https://discuss.ropensci.org/c/usecases), [para um tweet da rOpenSci e possível inclusão no boletim quinzenal da rOpenSci](https://discuss.ropensci.org/t/about-the-usecases-category/33). Também recomendamos que você adicione um link para o caso de uso em uma seção "use cases in the wild" do seu README.

- Quando você [liberar](#releasing) uma nova versão do seu pacote ou você o lança no CRAN pela primeira vez,
  
  - Faça uma solicitação pull para [R Weekly](https://github.com/rweekly/rweekly.org) com uma linha sobre a versão na seção "New Releases" (ou "New Packages" para a primeira versão do GitHub/CRAN).
  
  - Tweet sobre isso usando a hashtag "#rstats" e marque rOpenSci! Isso pode ajudar no envolvimento do colaborador/usuário. [Exemplo](https://twitter.com/opencpu/status/1003934871830622208).
  
  - Considere a possibilidade de enviar uma breve postagem sobre o lançamento para [Notas técnicas do rOpenSci](https://ropensci.org/technotes/). Entre em contato com o gerente da comunidade do rOpenSci (por exemplo, via Slack ou [info@ropensci.org](mailto:info@ropensci.org)). Consulte [as diretrizes sobre como contribuir com uma postagem de blog](https://blogguide.ropensci.org)).
  
  - Envie seu pacote para listas de pacotes, como [Visualizações de tarefas do CRAN](https://cran.r-project.org/web/views/) e [Visualizações de tarefas rOpenSci não-CRAN](https://github.com/search?utf8=%E2%9C%93&q=user%3Aropensci+%22task+view%22&type=Repositories&ref=searchresults).

- Se você optar por comercializar seu pacote dando uma palestra sobre ele em um encontro ou conferência (excelente ideia!)
  leia [este artigo de Jenny Bryan e Mara Averick](https://www.tidyverse.org/articles/2018/07/carpe-talk/).


