# Package Curation Policy {#curationpolicy}

```{block, type='summaryblock'}
This chapter summarizes a proposed curation policy for rOpenSci's
ongoing maintenance of packages developed as part of rOpenSci activities
and/or under the rOpenSci GitHub organization. This curation policy aims
to support these goals:

-   Ensure packages provided by rOpenSci are up-to-date and high quality

-   Provide clarity as to the development status and and review status
    of any software in rOpenSci repositories

-   Manage maintenance effort for rOpenSci staff, package authors, and
    volunteer contributors

-   Provide a mechanism to gracefully sunset packages while maintaining
    peer-review badging

```

Elements of infrastructure described
below needed for implementation of the policy are in some cases partly
built and in other cases not yet begun. We aim to adopt this policy in
part to prioritize work on these components.

## The package registry

-   The rOpenSci package
[registry](https://github.com/ropensci/roregistry)
is a central listing of R packages currently or formerly
maintained or reviewed by rOpenSci. It contains essential package
metadata including development and review status, and will be the
source of data for display on websites, badges, etc. It will allow
this listing to be maintained independently of package or
infrastructure hosting platforms.

## Staff-maintained packages

Staff-maintained packages are developed and maintained by rOpenSci staff
as part of rOpenSci projects. These packages may also be peer-reviewed
packages, but are not necessarily peer reviewed. Many are infrastructure
packages that fall out of scope for peer review.

-   Staff-maintained packages will be listed in the registry with tag
    "staff" and listed on rOpenSci's packages web page or similar
    venues with tag "staff"

-   These packages will be stored in the "ropensci" GitHub
    organization

-   Staff-maintained packages will be checked via rOpenSci's [custom CI
    system](https://status.ropensci.org/) to test that they build and test successfully across
    systems and that their documentation build correctly.

-   When the packages fail checks, rOpenSci staff will endeavour to fix
    changes, prioritizing packages based on user base (downloads),
    reverse dependencies, or strategic goals.

-   On a biannual or annual basis, rOpenSci will review all packages
    that have been failing for over a month to determine whether to transfer them to the ["ropensci-archive" GitHub organization](https://github.com/ropensci-archive).

-   Packages consistently failing and without an ongoing plan to return
    to active maintenance will move to "archive" status. When
    archived, staff packages will move to the "ropensci-archive"
    repository (to be created) and and gain the "archived" tag in
    the registry. They will not be checked via CI.

-   Archived packages will not be displayed by default on the packages
    web page. An option to "show archived packages" will display
    these with an "archived" tag.

-   Archived packages can be unarchived when the old or a new maintainer
    is willing to address the problems and wants to revive the
    package.

## Peer-reviewed packages

Peer-reviewed packages are those contributed to the rOpenSci by the
community and have passed through peer review. They need to be
[in-scope](#aims-and-scope)
at the time of submission to be reviewed.

-   Upon acceptance, these peer-reviewed packages are transferred from
    the author's GitHub to the "ropensci" GitHub organization

-   Peer-reviewed packages will be in the registry tagged as
    "peer-reviewed" and have a peer-reviewed badge in their README.

-   Peer-reviewed packages will be listed on rOpenSci's web page or
    similar venues with tag "peer-reviewed"

-   Peer-reviewed packages will be checked via rOpenSci's CI that they
    build and test successfully across systems and that their docs
    build correctly.

-   When packages fail on CI, rOpenSci's build system will notify the
    authors automatically. If on CRAN, it will also notify them of
    additional issues raised, opting peer-reviewed package authors in
    to this service by default (see [issue](https://github.com/ropenscilabs/cchecksapi/issues/13)).

-   Annually or bi-annually, rOpenSci staff will review packages in a
    failing state or have been failing for extended periods, and
    contact the authors to determine ongoing maintenance status and
    expected updates. Based on this exchange, rOpenSci may opt to
    retain the package's current status with the expectation of an
    updates, contribute support or seek a new maintainer, or transfer
    the package to "archived" status.

-   Based on user base (measured by downloads), reverse dependencies, or
    rOpenSci strategic goals, rOpenSci staff may support failing
    packages via PRs reviewed by package authors, or direct changes
    (if authors are unresponsive for approximately a month). rOpenSci
    will also provide support to package authors on request, both by
    staff and community volunteers, based on time available. We

-   At the author's request, or if authors are unresponsive to
    inquiries for approximately a month, rOpenSci may seek a new
    maintainer for select peer-reviewed packages it deems have high
    community value based on user base/downloads, reverse
    dependencies, or rOpenSci strategic goals.

-   When archived, these packages will move from the "ropensci" GitHub
    organization to the "ropensci-archive" organization (or author
    GitHub accounts if desired). They will gain the "archived" tag
    in the registry, and a "migrated" tag and "migrated-date"
    field indicating the date of migration and a URL for a new
    location if needed.. They will retain "peer-reviewed" tags and
    badges. They will not be checked via CI.

-   Archived packages will not be displayed by default. An option to
    "show archived packages" will display these with an "archived"
    tag.

-   Archived packages may be un-archived at authors' request if authors
    opt to resume maintenance.

## Legacy acquired packages

"Legacy" packages are packages not created or maintained by rOpenSci
staff and not peer reviewed, but are under the rOpenSci GitHub
organization(s) due to historical reasons. (Prior to establishing the
peer review process and its scope, rOpenSci absorbed packages from
various developers without well-defined criteria.)

-   rOpenSci will transfer legacy packages back to author organizations
    and repositories. If authors are uninterested, we will transfer
    them to the "ropensci-archive" repository. If packages are
    [[in-scope]{.underline}](https://devguide.ropensci.org/policies.html#aims-and-scope),
    rOpenSci will inquire if authors would like to submit them to the
    Software Review process.

-   Legacy packages transferred out to author organizations will not be
    listed in the package registry.

-   Legacy packages will be tagged "archived" in the package registry
    if they are in the ropensci-archive repository and unmaintained.

## Incubator packages

"Incubator" packages are in-development packages created by staff or
community members as part of community projects, such as those created
at unconferences

-   Incubator packages will live in the "ropensci-incubator"
    repository (to be renamed from "ropenscilabs")

-   Incubator packages will appear in the package registry with the
    "incubator" tag

-   Incubator packages will not appear on the website by default, but
    only if a "include incubator packages" option is checked.

-   Incubator packages will be built and tested via CI (if they have
    minimal package infrastructure), with documentation clearly
    labeled as incubator. Authors will not receive alerts for failing
    packages and status will appear in a different page or section of
    the testing server.

-   Biannually or annually, rOpenSci will contact incubator maintainers
    about repositories at least three months old, inquiring about
    development status and author preferences for migration to
    peer-review, ropensci-archive, or to author organizations. Based
    on response, package will be migrated immediately, peer review
    will be initiated, or migration will be deferred to the next
    review. Incubator packages will be migrated to ropensci-archive by
    default after one year.

-   Archived incubator packages will gain the "archived" tag and
    retain the "incubator" tag in the registry

-   Packages migrated to author organizations will remain in the
    registry with the "incubator" tag and a "migrated" tag, with a
    "migrated-date" field indicating the date of migration and a URL
    for the new location.

### Incubator non-R-packages

-   The "incubator" organization will also include non-R-package
    projects.

-   These projects will not be listed in the registry or appear on a web
    page, and will not be automatically built.

-   Migration policy will be the same as for R packages, with
    appropriate migration locations (e.g., ropenci-books)

-   If archived, non-R-packages will move to "ropensci-archive"

## Books

rOpenSci books are long-form documentation, often bookdown-formatted,
related to rOpenSci packages, projects, or themes, created by both
rOpenSci staff and community members.

-   Books will live in the "ropensci-books" organization

-   Books will be hosted at books.ropensci.org

-   Books may be mature or in-development, but must have minimal
    outlines/content before migrating into "ropensci-books" (e.g.
    from "ropensci-incubator").

-   The authorship and development status of a book should be clearly
    described on its home page and README.

-   rOpenSci may provide badges or templates (e.g., "In development,"
    "Community Maintained,") for authors to use on book home pages
    in the future
