# Cambio de mantenedores de paquetes {#changing-maintainers}

```{block, type="summaryblock"}
Este capítulo presenta nuestra guía para asumir el mantenimiento de un paquete.
```

## ¿Quieres dejar el mantenimiento de tu paquete?

Tenemos una sección de petición de colaboradores en nuestro boletín que sale cada dos semanas. La sección se llama *Llamada a colaboradores*. En esa sección destacamos los paquetes que buscan nuevos mantenedores. Si quieres dejar el papel de mantenedor de tu paquete, ponte en contacto con nosotros y podremos destacar tu paquete en nuestro boletín. Hasta ahora hemos tenido mucho éxito, encontrando nuevos mantenedores para seis de los seis paquetes.

## ¿Quieres encargarte del mantenimiento de un paquete?

Tenemos una sección de solicitud de colaboradores en nuestro boletín que sale cada dos semanas. La sección se llama *Llamada a colaboradores*. En esa sección destacamos los paquetes que buscan nuevos mantenedores. Si aún no estás suscrito al boletín, es una buena idea [suscribirte a](https://news.ropensci.org/) para recibir una notificación cuando haya un paquete que busque un nuevo mantenedor.

## Asumir el mantenimiento de un paquete

- Añádase como nuevo mantenedor en el archivo DESCRIPTION, con `role = c("aut", "cre")`y haz que el antiguo mantenedor `aut` sólo.
- Asegúrate de cambiar el mantenedor por tu nombre en cualquier otra parte del paquete, manteniendo al antiguo mantenedor como autor (por ejemplo, en el archivo de manual a nivel de paquete, CONTRIBUTING.md, CITATION, etc.)
- El sitio web [Guía de Colaboración](#collaboration) tiene orientaciones sobre cómo añadir nuevos mantenedores y colaboradores
- Los paquetes que han sido archivados o \[huérfanos\]\[\] en CRAN no necesitan el permiso del anterior mantenedor para ser retomados en CRAN. En estos casos, ponte en contacto con nosotros para que podamos ofrecerte la ayuda que necesites.
- Si el paquete no ha sido archivado por CRAN y hay un cambio de mantenedor, haz que el antiguo mantenedor envíe un correo electrónico a CRAN y ponga por escrito quién es el nuevo mantenedor. Asegúrate de mencionar ese correo electrónico sobre el cambio de mantenedor cuando envíes la primera versión nueva a CRAN. Si el antiguo mantenedor no está localizable o no envía este correo electrónico, ponte en contacto con el personal de rOpenSci.
- Si el antiguo mantenedor está localizable, programar una reunión te ayudará a conseguir la "disposición del terreno".

### Preguntas frecuentes para los nuevos mantenedores

- Hay algunos issues no resueltos del paquete que no sé cómo arreglar. ¿A quién puedo pedir ayuda?
  
  Depende; esto es lo que hay que hacer en diferentes situaciones:


```
- si se puede contactar con el antiguo mantenedor: ponte en contacto con él y pídele ayuda;
- rOpenSci slack: es bueno para obtener ayuda sobre problemas específicos o generales, consulta el canal #mantenimiento-de-paquetes;
- [Foro de discusión de rOpenSci](https://discuss.ropensci.org/c/package-development/29): este foro es una buena opción, siéntete libre de hacer cualquier pregunta allí;
- [Personal de rOpenSci](https://ropensci.org/about/#team): no dudes en ponerte en contacto con uno de nosotros por correo electrónico/enviando issues a GitHub, estaremos encantados de ayudarte;
- por supuesto, también hay ayuda general de R si eso se ajusta a tus necesidades: Foro de la comunidad de RStudio, StackOverflow, Twitter #rstats, etc.
```

- ¿Cuánto puedes/debes cambiar en el paquete?
  
  Para obtener ayuda general sobre cómo cambiar el código de un paquete, consulta la sección [Evolución del paquete](#evolution)
  sección.
  
  Al pensar en esto, hay muchas consideraciones.
  
  ¿Cuánto tiempo tienes que dedicar al paquete? Si tienes un tiempo muy limitado, lo mejor será que te centres en las tareas más críticas, sean las que sean para el paquete en cuestión. Si tienes mucho tiempo, tus objetivos pueden ser de mayor alcance.
  
  ¿Qué grado de madurez tiene el paquete? Si el paquete es maduro, es probable que mucha gente tenga código que dependa de la API del paquete (es decir, las funciones exportadas y sus parámetros). Además, si hay paquetes que dependen de tu paquete en CRAN, entonces tienes que comprobar que cualquier cambio que hagas no rompa esos paquetes. Cuanto más maduro sea el paquete, más cuidado deberás tener a la hora de hacer cambios, especialmente con los nombres de las funciones exportadas, sus parámetros y la estructura exacta de lo que devuelven las funciones exportadas. Es más fácil hacer cambios que sólo afecten a los aspectos internos del paquete.

## Tareas para el personal de rOpenSci

Como organización, a rOpenSci le interesa asegurarse de que los paquetes de nuestro conjunto estén disponibles mientras sean útiles para la comunidad. A medida que los mantenedores tengan que seguir adelante, en la mayoría de los casos intentaremos conseguir un nuevo mantenedor para cada paquete. Para ello, las siguientes tareas son responsabilidad del personal de rOpenSci.

- Si un repositorio no ha visto ninguna actividad (commits, issues, pull requests) en mucho tiempo, puede ser simplemente un paquete maduro con poca necesidad de cambios/etc., así que tenlo en cuenta.
- El actual mantenedor no ha respondido a las incidencias/solicitudes de extracción en muchos meses, a través de cualquiera de los correos electrónicos, los issue de GitHub o los mensajes de Slack:
  - Ponte en contacto con él y averigua cuál es la situación. Puede decir que le gustaría dejar de ser mantenedor, en cuyo caso busca un nuevo mantenedor
- El actual mantenedor está completamente desaparecido/no responde
  - Si esto ocurre, intentaremos ponernos en contacto con el mantenedor durante un máximo de un mes. Sin embargo, si la actualización del paquete es urgente, podemos utilizar nuestro acceso de administrador para realizar los cambios en su nombre.
- Haz un llamamiento en la sección "Call for Contributors" del boletín rOpenSci para un nuevo mantenedor - abre un issue en el [repo del boletín](https://github.com/ropensci/monthly/).


