---
repo-actions: true
aliases: 
  - marketing.html
---

# Marketing your package {#marketing}

```{block, type="summaryblock"}
We will help you promoting your package but here are some more things to keep in mind.
```

- If you hear of an use case of your package, please encourage its author to post the link to our [discussion forum in the Use Cases category](https://discuss.ropensci.org/c/usecases), [for a toot (Mastodon post) from rOpenSci and inclusion in the rOpenSci monthly newsletter](https://discuss.ropensci.org/t/about-the-usecases-category/33). We also recommend you to add a link to the use case in a "use cases in the wild" section of your README.

- Post about your package on Mastodon using the "#rstats" hashtag and tag rOpenSci! This might help with contributor/user engagement. Example posts from rOpenSci itself: [A package a day](hachyderm.io/@rOpenSci/111611705648653729), [Help wanted post](hachyderm.io/@rOpenSci/111460729804231877), [Use cases](hachyderm.io/@rOpenSci/111371091053569287), [Welcome post]( hachyderm.io/@rOpenSci/111342069863172097).

- When you [release](#releasing) a new version of your package or release it to CRAN for the first time,
  
  - Make a pull request to [R Weekly](https://github.com/rweekly/rweekly.org) with a line about the release under the "New Releases" section (or "New Packages" for the first GitHub/CRAN release).
  
  - Post about it on social media.
  
  - Consider submitting a short post about the release to [rOpenSci tech notes](https://ropensci.org/technotes/). Contact rOpenSci Community Manager, (e.g. via Slack or [info@ropensci.org](mailto:info@ropensci.org)). Refer to [the guidelines about contributing a blog post](https://blogguide.ropensci.org)).
  
  - Submit your package to lists of packages such as [CRAN Task Views](https://cran.r-project.org/web/views/).

- If you choose to market your package by giving a talk about it at a meetup or conference (excellent idea!)
  read [this article of Jenny Bryan's and Mara Averick's](https://www.tidyverse.org/articles/2018/07/carpe-talk/).


