# Política de conservación de paquetes {#curationpolicy}

```{block, type="summaryblock"}
Este capítulo resume una política de conservación propuesta para el mantenimiento continuo de rOpenSci
mantenimiento continuo de los paquetes desarrollados como parte de las actividades de rOpenSci
y/o bajo la organización rOpenSci GitHub. Esta política de conservación pretende
apoyar estos objetivos:

- Garantizar que los paquetes proporcionados por rOpenSci estén actualizados y sean de alta calidad

- Proporcionar claridad en cuanto al estado de desarrollo y el estado de revisión
    de cualquier software en los repositorios de rOpenSci

- Gestionar el esfuerzo de mantenimiento para el personal de rOpenSci, los autores de los paquetes y
    contribuyentes voluntarios

- Proporcionar un mecanismo para la desaparición gradual de los paquetes, manteniendo al mismo tiempo
    la etiqueta de revisión por pares

```

Los elementos de infraestructura descritos
necesarios para la aplicación de la política están, en algunos casos, parcialmente
construidos y en otros casos aún no se han iniciado. Nuestro objetivo es adoptar esta política en
parte para priorizar el trabajo en estos componentes.

## El registro de paquetes

- El registro de paquetes rOpenSci
  [registro](https://github.com/ropensci/roregistry)
  es una lista central de paquetes de R mantenidos o revisados por rOpenSci.
  contiene metadatos esenciales de los paquetes, incluyendo el estado de desarrollo y revisión.
  paquete, incluyendo el estado de desarrollo y revisión, y será la fuente
  fuente de datos para su visualización en sitios web, etiquetas, etc. Permitirá
  que este listado se mantenga independientemente de las plataformas de
  plataformas de alojamiento de infraestructuras.

## Paquetes mantenidos por el personal

Los paquetes mantenidos por el personal son desarrollados y mantenidos por el personal de rOpenSci
como parte de los proyectos de rOpenSci. Estos paquetes también pueden ser revisados por pares
pero no son necesariamente revisados por pares. Muchos son paquetes de infraestructura
de infraestructura que están fuera del alcance de la revisión por pares.

- Los paquetes mantenidos por el personal aparecerán en el registro con la etiqueta
  "staff\_maintained" y aparecerán en la página web de paquetes de rOpenSci o en lugares similares
  con la etiqueta "staff-maintained".

- Estos paquetes se almacenarán en la organización GitHub "ropensci
  organización

- Los paquetes mantenidos por el personal y sus documentos serán creados por rOpenSci
  [sistema](https://status.ropensci.org/). Este sistema no envía notificaciones
  pero emite los resultados en forma de estado de commit de GitHub (marca de verificación roja o cruz roja).

- Cuando los paquetes no superen las comprobaciones, el personal de rOpenSci se esforzará en corregir
  los cambios, priorizando los paquetes en función de la base de usuarios (descargas)
  las dependencias inversas o los objetivos estratégicos.

- Con carácter bianual o anual, rOpenSci revisará todos los paquetes
  que lleven más de un mes sin funcionar para determinar si se transfieren al ["organización GitHub "ropensci-archive](https://github.com/ropensci-archive).

- Los paquetes que fallan constantemente y que no tienen un plan para volver
  al mantenimiento activo pasarán al estado de "archivo". Cuando
  archivados, los paquetes del personal pasarán al repositorio "ropensci-archive"
  repositorio (por crear) y ganarán el tipo "archivado" en
  el registro. No se construirán en el sistema rOpenSci.

- Los paquetes archivados no se mostrarán por defecto en la página web de paquetes
  en la página web de paquetes. Una pestaña especial de las páginas de paquetes mostrará
  estos con `"type": "archived"`
  que hayan sido revisados por pares o mantenidos por el personal.

- Los paquetes archivados pueden desarchivarse cuando el antiguo o un nuevo mantenedor
  esté dispuesto a solucionar los problemas y quiera revivir el
  paquete. Para ello, ponte en contacto con [contacta con rOpenSci](https://ropensci.org/contact/).
  Se transfieren a la organización ropenscilabs.

## Paquetes revisados por pares

Los paquetes revisados por pares son aquellos aportados a rOpenSci por la
comunidad y han pasado por la revisión por pares. Tienen que estar
[en el ámbito](#aims-and-scope)
en el momento del envío para ser revisados.

- Una vez aceptados, estos paquetes revisados por pares se transfieren desde
  el GitHub del autor a la organización GitHub "ropensci

- Los paquetes revisados por pares estarán en el registro etiquetados como
  "revisado por pares" y tendrán una etiqueta de revisado por pares en su LÉAME.

- Los paquetes revisados por pares aparecerán en la página web de rOpenSci o
  lugares similares con la etiqueta "peer-reviewed".

- Los paquetes revisados por pares y su documentación serán construidos por el sistema rOpenSci
  [sistema](https://status.ropensci.org/). Este sistema no envía notificaciones
  pero muestra los resultados como el estado de las confirmaciones de GitHub (marca de verificación roja o cruz roja).

- Si los paquetes están en CRAN, los autores de los paquetes pueden elegir suscribirse a las [notificaciones
  de la API de comprobaciones de CRAN](https://docs.cranchecks.info/#notifications).

- Anualmente o bianualmente, el personal de rOpenSci revisará los paquetes en un
  estado de fallo o que han estado fallando durante largos periodos, y
  se pondrá en contacto con los autores para determinar el estado de mantenimiento y las
  actualizaciones previstas. Basándose en este intercambio, rOpenSci puede optar por
  mantener el estado actual del paquete con la expectativa de una
  actualizaciones, contribuir con el apoyo o buscar un nuevo mantenedor, o transferir


```
el paquete al estado "archivado".
```

- En función de la base de usuarios (medida por las descargas), las dependencias inversas o
  objetivos estratégicos de rOpenSci, el personal de rOpenSci puede apoyar los paquetes
  paquetes fallidos a través de PRs revisados por los autores del paquete, o cambios directos
  (si los autores no responden durante aproximadamente un mes). rOpenSci
  también proporcionará apoyo a los autores de paquetes a petición, tanto del
  personal y voluntarios de la comunidad, en función del tiempo disponible.

- A petición del autor, o si los autores no responden a
  a las consultas durante aproximadamente un mes, rOpenSci puede buscar un nuevo
  un nuevo mantenedor para determinados paquetes revisados por pares que considere que tienen un alto
  valor para la comunidad en función de la base de usuarios/descargas, dependencias
  dependencias inversas, o los objetivos estratégicos de rOpenSci.

- Cuando se archiven, estos paquetes pasarán de la organización "ropensci" de GitHub
  a la organización "ropensci-archive" (o a las cuentas de autor
  GitHub si lo deseas), siguiendo [guía de transferencia](#archivalguidance). Obtendrán el tipo "archivado
  en el registro. Conservarán las etiquetas e insignias de "revisión por pares".
  etiquetas. No se construirán en el sistema rOpenSci.

- Los paquetes archivados no se mostrarán por defecto. Una pestaña especial de paquetes
  se mostrará `display these with `"tipo": "archivados"\`.
  que fueron revisados por los compañeros o mantenidos por el personal.

## Paquetes heredados adquiridos

Los paquetes "heredados" son paquetes no creados ni mantenidos por el personal de rOpenSci
y no revisados por pares, pero están bajo la organización de rOpenSci GitHub
debido a razones históricas. (Antes de establecer el
proceso de revisión por pares y su alcance, rOpenSci absorbía paquetes de
varios desarrolladores sin criterios bien definidos).

- rOpenSci transferirá los paquetes heredados de nuevo a las organizaciones de autores
  y repositorios. Si los autores no están interesados, los transferiremos
  al repositorio "ropensci-archive" siguiendo [guía de transferencia](#archivalguidance). Si los paquetes están
  [en el ámbito de aplicación](https://devguide.ropensci.org/policies.html#aims-and-scope),
  rOpenSci preguntará si los autores desean someterlos al
  proceso de revisión del software.

- Los paquetes heredados no se incluirán en el registro de paquetes.

- Se pueden hacer excepciones para los paquetes que son partes vitales del ecosistema de paquetes de R y/o rOpenSci que son supervisados activamente por el personal.

## Paquetes incubadores

Los paquetes "incubadores" son paquetes en desarrollo creados por el personal o
miembros de la comunidad como parte de proyectos comunitarios, como los creados
en las desconferencias

- Los paquetes incubadores vivirán en la organización "ropenscilabs".

- Los paquetes de la incubadora aparecerán en el registro de paquetes con la etiqueta
  etiqueta "incubadora".

- Los paquetes de la incubadora no aparecerán por defecto en el sitio web, pero
  las páginas de paquetes incluirán una pestaña de "paquetes experimentales".

- Los paquetes de la incubadora y su documentación serán creados por rOpenSci
  [sistema](https://status.ropensci.org/). Este sistema no envía notificaciones
  pero emite los resultados como estado de commit de GitHub (marca de verificación roja o cruz roja).
  Los documentos indicarán claramente que el paquete es experimental.

- Semestral o anualmente, rOpenSci se pondrá en contacto con los mantenedores de la incubadora
  sobre los repositorios de al menos tres meses de antigüedad, preguntando por
  el estado de desarrollo y las preferencias del autor para la migración a
  revisión por pares, ropensci-archivo, o a organizaciones de autores. En base a
  en la respuesta, el paquete se migrará inmediatamente, se iniciará la revisión por pares
  se iniciará la revisión por pares, o la migración se aplazará hasta la próxima
  revisión. Los paquetes de la incubadora se migrarán a ropensci-archivo por
  por defecto después de un año, siguiendo [guía de transferencia](#archivalguidance).

- Los paquetes de incubadora archivados ganarán el tipo "archivado".

### Paquetes no R de la incubadora

- La organización "incubadora" también incluirá proyectos que no sean paquetes R
  proyectos.

- Estos proyectos no aparecerán en el registro ni en una página web
  y no se construirán automáticamente.

- La política de migración será la misma que para los paquetes R, con
  ubicaciones de migración adecuadas (por ejemplo, ropensci-libros)

- Si se archivan, los paquetes que no son R se trasladarán a "ropensci-archivo" siguiendo [guía de transferencia](#archivalguidance).

## Libros

Los libros de rOpenSci son documentación larga, a menudo con formato de libro,
relacionados con los paquetes, proyectos o temas de rOpenSci, creados tanto por el
personal de rOpenSci y miembros de la comunidad.

- Los libros vivirán en la organización "ropensci-books".

- Los libros se alojarán en books.ropensci.org

- Los libros pueden estar maduros o en desarrollo, pero deben tener un mínimo de
  contenido antes de migrar a "ropensci-libros" (por ejemplo
  desde "ropenscilabs").

- La autoría y el estado de desarrollo de un libro deben estar claramente
  descrito en su página de inicio y en el README.

- rOpenSci puede proporcionar etiquetas o plantillas (por ejemplo, "En desarrollo,"
  "Mantenido por la comunidad") para que los autores los utilicen en las páginas de inicio de los libros
  en el futuro


