# Onboarding Guide for Authors

-   Consult our [policies](#policies) see if your package meets our criteria for fitting into our suite and not overlapping with other packages.
    -    If you are unsure whether a package meets our criteria, feel free to open an issue as a pre-submission inquiry to ask if the package is appropriate.
-   Follow our packaging style guide to ensure your package
  meets our style and quality criteria.
    -   If you would like your package also submitted to
        [Journal of Open-Source Software](http://joss.theoj.org/) (JOSS), it should include a `paper.md` file describing the package. More detail on JOSS's requirements can be found [at their website](http://joss.theoj.org/about#author_guidelines).
    -   If you choose this option you should *not* submit your package to JOSS separately. It will be evaluated by JOSS based on the rOpenSci review.
-   Next, [open a new issue](https://github.com/ropensci/onboarding/issues/new) in
this repository and fill out the template.
-   An [editor](#editors) will review your submission within 5 business days and respond with next steps. The editor may assign the package to reviewers, request that the package be updated to meet minimal criteria before review, or reject the package due to lack of fit or overlap.
-   If your package meets minimal criteria, the editor will assign  1-3 reviewers. They will be asked to provide reviews as comments on your issue within 3 weeks.
-   We ask that you respond to reviewers' comments within 2 weeks of the last-submitted review, but you may make updates to your package or respond at any time. Here is [an author response example](https://github.com/ropensci/onboarding/issues/160#issuecomment-355043656).  We encourage ongoing conversations between authors and reviewers. See the [reviewing guide](reviewing_guide.md) for more details.
-   Once your package is approved, we will provide further instructions on transferring your repository to the rOpenSci repository.

Our [code of conduct](#code-of-conduct) is mandatory for everyone involved in our review process.
