#  (PART) Onboarding Packages {-}

# Onboarding, Why? What?

rOpenSci's [suite of packages](https://ropensci.org/packages/) is partly contributed by staff members and partly contributed by community members, which means the suite stems from a great diversity of skills and experience of developers. How to ensure quality for the whole set? That's where onboarding comes into play: packages contributed by the community undergo a transparent, constructive, non adversarial and open review process. For that process relying mostly on volunteer work, [associate editors](https://github.com/ropensci/onboarding#associate-editors) manage the incoming flow and ensure progress of submissions; authors create, submit and improve their package; [reviewers](https://github.com/ropensci/onboarding#reviewers), two per submission, examine the software code and user experience. [This blog post](https://www.numfocus.org/blog/how-ropensci-uses-code-review-to-promote-reproducible-science/) written by rOpenSci onboarding editors is a good introduction to rOpenSci onboarding. Other blog posts about onboarding itself and onboarded packages can be find [via the "onboarding" tag on rOpenSci blog](https://ropensci.org/tags/onboarding/).

Technically, we make the most of [GitHub](https://github.com/) infrastructure: each package onboarding process is an issue in the [ropensci/onboarding GitHub repository](https://github.com/ropensci/onboarding/). For instance, click [here](https://github.com/ropensci/onboarding/issues/24) to read the onboarding review thread of my `ropenaq` package: the process is an ongoing conversation until acceptance of the package, with two external reviews as important milestones. Furthermore, we use GitHub features such as the use of issue templates (as submission templates), and such as labelling which we use to track progress of submissions (from editor checks to approval).

## Why submit your package to rOpenSci?

-   First, and foremost, we hope you submit your package for review **because you
    value the feedback**.  We aim to provide useful feedback to package authors
    and for our review process to be open, non-adversarial, and focused on
    improving software quality.
-   Once aboard, your package will continue to receive **support from rOpenSci
    members**.  You'll retain ownership  and control of of your package, but we
    can help with ongoing maintenance issues such as those associated with
    updates to R and dependencies and CRAN policies.
-   rOpenSci will **promote your package** through our [web
    page](https://ropensci.org/packages/), [blog](https://ropensci.org/blog/),
    and [social media](https://twitter.com/ropensci).  Packages in our suite
    are also distributed via our [drat repository](http://packages.ropensci.org/)
    and [Docker images](https://hub.docker.com/r/rocker/ropensci/), and listed
    in our [task views](https://github.com/search?utf8=%E2%9C%93&q=user%3Aropensci+%22task+view%22&type=Repositories&ref=searchresults).
-   rOpenSci **packages can be cross-listed** with other repositories such as CRAN
    and BioConductor.
-   rOpenSci packages that contain a short accompanying paper can, after review,
    be automatically submitted to the
    [Journal of Open-Source Software](http://joss.theoj.org/) for fast-tracked
    publication.

## Why review packages for rOpenSci?

-   As in any peer-review process, we hope you choose to review **to give back
    to the rOpenSci and scientific communities.**  Our mission to expand
    access to scientific data and promote a culture of reproducible research
    is only possible through the volunteer efforts of community members like you.
-   Review is a two-way conversation. By reviewing packages, you'll have the
    chance to **continue to learn development practices from authors and
    other reviewers**.
-   The open nature of our review process allows you to **network and meet
    colleagues and collaborators** through the review process.  Our community
    is friendly and filled with supportive members expert in R development and
    many other areas of science and scientific computing.
-   To volunteer to be one of our reviewers, just click [here](https://ropensci.org/onboarding/) to fill out a short form providing your contact
information and areas or expertise. We
    are always looking for more reviewers with both general package-writing experience
    and domain expertise in the fields packages are used for.

## Editors and reviewers

### Associate editors

rOpenSci's onboarding process is run by:

* [Noam Ross](https://github.com/noamross), EcoHealth Alliance
* [Scott Chamberlain](https://github.com/sckott), rOpenSci
* [Karthik Ram](https://github.com/karthik), rOpenSci
* [Maëlle Salmon](https://github.com/maelle), rOpenSci

### Reviewers

We are grateful to the following individuals who have offered up their time and expertise to review packages submitted to rOpenSci.

```{r reviewers, echo=FALSE, results='asis'}
library("airtabler")
editors <- c("Noam Ross", "Scott Chamberlain", "Karthik Ram", "Maëlle Salmon")
reviewers <- air_get(base = "appZIB8hgtvjoV99D", table = "Reviewers", combined_result = FALSE)
reviewers2 <- air_get(base = "appZIB8hgtvjoV99D", table = "Reviewers", combined_result = FALSE, offset=get_offset(reviewers))
reviewers <- rbind(reviewers$fields[, c('name', 'github', 'Reviews')], reviewers2$fields[, c('name', 'github', 'Reviews')])
reviewers <- reviewers[purrr::map_lgl(reviewers$Reviews, ~!is.null(.)) & !(reviewers$name %in% c(editors, "???")), ]
reviewers <- reviewers[order(reviewers$name), ]
cat(paste0("[", reviewers$name, "](https://github.com/", reviewers$github, ")", collapse = " \U00B7 "))
```
