# Prefacio {.unnumbered}

¡Te damos la bienvenida! Este libro es una guía para autoras/es, encargadas/os, revisoras/es y editoras/es de rOpenSci.

La [primera sección del libro](#building) contiene nuestras recomendaciones para crear y probar los paquetes de R.

La [segunda sección](#softwarereviewintro) está dedicada al proceso de revisión por pares de software de rOpenSci: en qué consiste, nuestras políticas y las guías específicas para orientar a quienes crean, mantienen, revisan y editan a lo largo del proceso. 
Para la *revisión de software estadístico*, consulta la  [página web del proyecto y los recursos asociados](https://ropensci.org/stat-software-review/).

La [tercera y última sección](#collaboration) presenta nuestras buenas prácticas para hacer crecer tu paquete una vez que ha sido incorporado a rOpenSci: cómo colaborar con otras/os desarrolladoras/es, cómo documentar cada versión, cómo promover tu paquete y cómo aprovechar GitHub como plataforma de desarrollo.
La tercera sección también incluye un [capítulo para quienes desean comenzar a contribuir a los paquetes de rOpenSci](#contributingguide).

Esperamos que esta guía te resulte útil y clara, y agradecemos tus sugerencias en las [issues del libro](https://github.com/ropensci/dev_guide/issues). 
¡Mucho éxito desarrollando paquetes de R!

El equipo editorial de rOpenSci.

Este libro es un documento vivo.
Puedes ver las actualizaciones de nuestras buenas prácticas y políticas a través de las [notas de cada versión](#booknews).  
Puedes citar este libro utilizando [sus metadatos de Zenodo y su DOI](https://doi.org/10.5281/zenodo.2553043).

```{r}
#| echo: false
#| results: 'asis' 
#| warning: false
cat("\n``bibtex\n")
u <- "https://zenodo.org/record/2553043" # la URL universal redirige a la última
s <- rvest::session(u)
u <- paste0(s$url, "/export/hx") # redirigido
out <- rvest::read_html(u)
bibentry <- rvest::html_text(rvest::html_element(out, "pre"))
cat(bibentry)
cat("\n```\n")
```

*Si quieres contribuir sugerencias o correcciones a este libro, visita [el repositorio de GitHub](https://github.com/ropensci/dev_guide) y, en particular, [la guía de contribución](https://github.com/ropensci/dev_guide#contributing). ¡Gracias!*

*Agradecemos a las/os autoras/es, encargadas/os, revisoras/es y editoras/es invitadas/os por ayudarnos a mejorar el sistema y esta guía a lo largo de los años. Gracias también a las siguientes personas que han contribuido a esta guía y a sus versiones anteriores: [Katrin Leinweber](https://github.com/katrinleinweber), [John Baumgartner](https://github.com/johnbaums), [François Michonneau](https://github.com/fmichonneau), [Christophe Dervieux](https://github.com/cderv), [Lorenzo Busetto](https://github.com/lbusett), [Ben Marwick](https://github.com/benmarwick), [Nicholas Horton](https://github.com/nicholasjhorton), [Chris Kennedy](https://github.com/ck37), [Mark Padgham](https://github.com/mpadge), [Jeroen Ooms](https://github.com/jeroen), [Sean Hughes](https://github.com/seaaan), [Jan Gorecki](https://github.com/jangorecki), [Joseph Stachelek](https://github.com/jsta), [Dean Attali](https://github.com/daattali), [Julia Gustavsen](https://github.com/jooolia), [Nicholas Tierney](https://github.com/njtierney), [Rich FitzJohn](https://github.com/richfitz), [Tiffany Timbers](https://github.com/ttimbers), [Hilmar Lapp](https://github.com/hlapp), [Miles McBain](https://github.com/milesmcbain), [Bryce Mecum](https://github.com/amoeba), [Jonathan Carroll](https://github.com/jonocarroll/), [Carl Boettiger](https://github.com/cboettig/), [Florian Privé](https://github.com/privefl), [Stefanie Butland](https://github.com/stefaniebutland), [Daniel Possenriede](https://github.com/dpprdan/), [Hadley Wickham](https://github.com/hadley/), [Mauro Lepore](https://github.com/maurolepore/), [Matthew Fidler](https://github.com/mattfidler), [Luke McGuinness](https://github.com/mcguinlu), [Aaron Wolen](https://github.com/aaronwolen), [Indrajeet Patil](https://github.com/IndrajeetPatil), [Kevin Wright](https://github.com/kwstat), [Will Landau](https://github.com/wlandau), [Hugo Gruson](https://github.com/Bisaloo),
[Hao Ye](https://github.com/ha0ye),
[Sébastien Rochette](https://github.com/statnmap),
[Edward Wallace](https://github.com/ewallace/), 
[Alexander Fischer](https://github.com/s3alfisc/). 
Por favor, avísanos si nos olvidamos de reconocer tu contribución.*


