 

# Gerenciamento editorial {#editorialmanagement}

```{block, type="summaryblock"}
Orientações para gerenciar a equipe editorial e também sobre [como gerenciar o lançamento de um guia de desenvolvimento] (#bookrelease).
```

## Recrutamento de novos editores {#recruiting-new-editors}

O recrutamento de novos editores e a manutenção de um conselho editorial suficiente e equilibrado é responsabilidade da [Líder de Revisão de Software](https://ropensci.org/about/#team) com o apoio e a orientação do conselho editorial.

Etapas:

- Inicie um canal privado para discussão (para que você não tenha um histórico no canal de editores no qual futuros editores entrarão, o que pode ser incômodo).

- Marque os editores na conversa para garantir que eles recebam uma notificação, pois este é um tópico importante.

- Espere que a maioria dos editores se manifeste antes de convidar alguém. Dê a eles uma semana para responder.

## Convidando um(a) novo(a) editor(a) {#inviting-a-new-editor}

- Um(a) candidato(a) pode começar como um(a) [editor(a) convidado(a)](#guesteditor).

- Envie um e-mail.

```
Gostaríamos de convidá-lo a fazer parte do conselho editorial da rOpenSci como membro efetivo. [RAZÕES ESPECÍFICAS PARA O CONVITE (MENCIONAR CONTRIBUIÇÕES PARA A rOpenSci)].
Acreditamos que você seria um excelente incremento à equipe.

[SE FOR EDITOR CONVIDADO -> Você está familiarizado(a) com a função do editor, pois já foi editor(a) convidado(a)]. Nosso objetivo é que os editores lidem com quatro pacotes por ano ([SE FOR EDITOR CONVIDADO -> incluindo o pacote que você acabou de finalizar!]).
Pedimos que editores assumam um compromisso informal de servir por dois anos, reavaliando sua participação depois deste período.
Em um curto prazo, qualquer editor pode se recusar a lidar com um pacote ou argumentar por exemplo “Estou muito ocupado e não posso lidar com um novo pacote por algumas semanas”.

Além de lidar com pacotes, os editores participam das decisões editoriais do grupo, como, por exemplo, se um pacote está dentro do escopo e determinando atualizações em nossas políticas. 
Geralmente, fazemos esse trabalho por meio do Slack, que esperamos que os editores possam verificar regularmente.
Também, fazemos chamadas com o conselho editorial anualmente.
Ademais, alternamos as responsabilidades do editor-chefe (decisões de escopo de primeira instância e designação de editores) entre o conselho editorial a cada três meses.
Você terá a oportunidade de participar desse rodízio depois de fazer parte do conselho por algum tempo, geralmente isso significa pelo menos seis meses. 
Alguns de nós também assumem projetos maiores para aprimorar o processo de revisão por pares, porém isso é opcional.

Esperamos que você faça parte do conselho!
Este é um momento empolgante para a revisão por pares na rOpenSci.

Por favor, reflita sobre a nossa oferta e faça perguntas se algo não estiver claro. Nos informe se você pode juntar-se a equipe rOpenSci.

Atenciosamente,
[EDITOR], em nome do Conselho Editorial da rOpenSci
```

## Integrando um(a) novo(a) editor(a) ao time {#onboarding-a-new-editor}

- Informe o(a) gerente da comunidade rOpenSci para
  
  - Novo(a) editor(a) seja adicionado ao [site da rOpenSci](https://github.com/ropensci/roweb3/#team-member).
  - criar uma nova postagem no blog da rOpenSci para introduzir os(as) novos(as) editores(as).

- Se eles ainda não fizeram este passo como editores convidados, solicite que ativem [a autenticação de dois fatores (2FA) para o GitHub](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa).

- Convide os novo(a) editor(a) para integrar a organização da rOpenSci no GitHub como parte da [equipe editorial da rOpenSci](https://github.com/orgs/ropensci/teams/editors) e da equipe [`data-pkg-editors`](https://github.com/orgs/ropensci/teams/data-pkg-editors) ou [`stats-board`](https://github.com/orgs/ropensci/teams/stats-board) subequipe, conforme for apropriado.
  Isso dará as permissões apropriadas e permitirá receber notificações específicas da equipe.

- Os editores precisam acessar o banco de dados sobre revisão de software no AirTable (o link está na descrição do canal `editors-only` no Slack).

- Os editores precisam ter acesso ao canal privado de editores no espaço de trabalho do Slack da rOpenSci (e ao espaço de trabalho do Slack em geral, caso não o tenham feito anteriormente; nesse caso, peça ao gerente da comunidade da rOpenSci).

- Publique uma mensagem de boas-vindas aos novos editores no canal, marcando todos os editores na mensagem.

- No espaço de trabalho do Slack, os novos editores precisam ser adicionados à "equipe de editores" para que sejam notificados também quando alguém marcar uma mensagem com `@editors`.

- Adicionar os nomes dos novos editores a/ao:
  
  - [lista de autores do Guia Dev](https://github.com/ropensci/dev_guide/blob/main/index.Rmd)
  - [capítulo do Guia Dev que introduz a revisão de software](https://github.com/ropensci/dev_guide/blob/main/softwarereview_intro.Rmd) (em dois locais neste arquivo, como editores e um pouco abaixo para removê-los da lista de revisores)
  - [software-review README](https://github.com/ropensci/software-review/blob/main/README.Rmd) (em dois lugares nesse arquivo também)

Tanto o Guia Dev quanto o README são automaticamente renderizados por meio do processo de integração contínua.

- Adicione os novos editores à [https://github.com/orgs/ropensci/teams/editors/members](https://github.com/orgs/ropensci/teams/editors/members)


## Desvincular um(a) editor(a) {#offboarding-an-editor}

- Agradeça o(a) editor(a) por seu trabalho!

- Remova este(a) editor(a) do canal reservado para editores, e também da "equipe de editores" do Slack.

- Remova este(a) editor(a) de [https://github.com/orgs/ropensci/teams/editors/members](https://github.com/orgs/ropensci/teams/editors/members) e da subequipe.

- Informe o gerente da comunidade do rOpenSci ou outro membro da equipe para que este(a) editor(a) possa ser transferido(a) para a parte de ex-membros no site da rOpenSci.

- Remova o acesso deles ao espaço de trabalho do Airtable.

- Removê-los do
  
  - [capítulo do Guia Dev que apresenta a revisão de software](https://github.com/ropensci/dev_guide/blob/main/softwarereview_intro.Rmd) (em dois locais neste arquivo, como editores e um pouco abaixo para removê-los da lista de revisores)
  - [software-review README](https://github.com/ropensci/software-review/blob/main/README.Rmd) (em dois lugares nesse arquivo também)
    Tanto o Guia Dev quanto o README da revisão de software são automaticamente compilados por meio do processo de integração contínua.

## Colocando o sistema em pausa {#vacation}

Se você quiser colocar o sistema em uma pausa, por exemplo, durante as férias, antes de sair:

- Adicione uma mensagem de férias ao campo `about` dos templates de issues. [Exemplo de PR](https://github.com/ropensci/software-review/pull/679/files).
- Adicione uma mensagem de férias à resposta de boas-vindas padrão do bot. [Exemplo de PR](https://github.com/ropensci-org/buffy/pull/108).

Ao retomar as atividades:

- Remover a mensagem de férias dos templates de issues. [Exemplo de PR](https://github.com/ropensci/software-review/pull/680).
- Remover a mensagem de férias da resposta de boas-vindas padrão do bot. [Exemplo de commit](https://github.com/ropensci-org/buffy/commit/500cfa07ca9dbaa138ca63eb255996e6f7331088).

## Gerenciando o lançamento de um guia de desenvolvimento {#bookrelease}

Se você estiver encarregado de gerenciar uma versão do livro que está lendo, use [o guia de lançamento de livros](#bookreleaseissue) como um modelo de _issue_ a ser publicado [no rastreador de problemas do guia de desenvolvimento](https://github.com/ropensci/dev_guide/issues). Não hesite em fazer perguntas a outros editores.

### Governança do guia de desenvolvimento {#devguidegov}

Para alterações muito pequenas no guia de desenvolvimento, não é necessária fazer revisão de _pull request_ (PR). Para alterações maiores, solicite a revisão de pelo menos alguns editores (se nenhum deles participou da discussão relacionada à alteração, solicite uma revisão de todos eles no GitHub e, na ausência de qualquer reação, faça o _merge_ após 1 semana).

Duas semanas antes do lançamento de um guia de desenvolvimento, uma vez que o PR do dev para o _master_ **e a postagem do blog de lançamento** estiverem prontos para revisão, todos os editores devem receber um _ping_ no GitHub ("solicitação de revisão" no PR de dev para _master_) e do Slack, mas o lançamento não precisa que todos eles aprovem explicitamente o lançamento.

### Postagem no blog sobre um lançamento {#releaseblogpost}

A postagem no blog sobre um lançamento será revisada [por editores](#devguidegov) e um dos `@ropensci/blog-editors`.

#### Conteúdo {#content}

Consulte a [orientação geral sobre blogs da rOpenSci](https://blogguide.ropensci.org/) e as orientações mais específicas abaixo.

[Primeiro exemplo de uma postagem desse tipo](https://ropensci.org/blog/2019/05/16/dev-guide-update/); [segundo exemplo](https://ropensci.org/blog/2019/10/08/dev-guide-update-fall19/).

A postagem no blog deve mencionar todos os itens importantes do [changelog](#booknews), organizados em (sub)seções: e.g., uma seção sobre uma grande mudança A, outra sobre uma grande mudança B e uma sobre as mudanças menores agrupadas. Mencione as alterações mais importantes primeiro.

Para cada alteração feita por um colaborador externo, agradeça-o explicitamente usando as informações do _changelog_. Por exemplo, `[Matt Fidler](https://github.com/mattfidler/) modificou nossa seção sobre mensagens de console [ropensci/dev_guide#178](https://github.com/ropensci/dev_guide/pull/178)`.

No final da postagem, mencione as próximas alterações vinculando-as a problemas abertos no rastreador de problemas e convide os leitores a contribuir com o guia de desenvolvimento abrindo _issues_ e participando de discussões abertas. Modelo de conclusão:

```markdown
Nesta postagem, resumimos as alterações incorporadas em nosso livro [“rOpenSci Packages: Development, Maintenance, and Peer Review”] (https://devguide.ropensci.org/) nos últimos X meses.

Somos gratos por todas as contribuições que tornaram possível esse lançamento.

Já estamos trabalhando em atualizações para a nossa próxima versão, como _issue1_, _issue2_.

Confira o [issue tracker] (https://github.com/ropensci/dev_guide/issues/) se você quiser contribuir.

```

#### Autoria {#authorship}

O editor que está escrevendo a postagem é o primeiro autor, os outros editores estão listados em ordem alfabética.
